services:

  # collector
  otel-collector:
    # https://opentelemetry.io/ja/docs/collector/installation/#docker-compose
    image: otel/opentelemetry-collector-contrib:0.139.0
    volumes:
      - type: bind
        source: ./otel-collector-config.yaml
        target: /etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - prometheus
  
  # Prometheus
  prometheus:
    image: prom/prometheus:v3.7.3
    ports:
      - "9090:9090"
    command:
      # Dockerfileに記載の command
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      # 追加分
      - "--web.enable-remote-write-receiver"

